version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-test-deploy:
    docker:
      - image: circleci/python:2.7
    environment:
      HOST: \$RDS_HOSTNAME
      PASS: \$RDS_PASSWORD
      USER: \$RDS_USERNAME
      DB: \$RDS_DATABASE

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "What was my custom environment variable?"
          command: echo ${RDS_HOSTNAME}
      - run:
          name: Install requirements.txt 
          command: |
            pip install -r requirements.txt
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Test code
          command: |
            python test.py
      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb init --region us-west-2 --platform docker cicdpipe
            eb use cicdfinal --profile eb-cli --region us-west-2
            eb deploy -v --staged --profile eb-cli

workflows:
  main:
    jobs:
      - build-test-deploy
